# Generated by Django 3.1.5 on 2021-01-21 03:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMRContador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=150, null=True, verbose_name='Región')),
                ('numeroCuenta', models.IntegerField(blank=True, null=True, verbose_name='Número de cuenta')),
                ('numeroCliente', models.IntegerField(blank=True, null=True, verbose_name='Número de cliente')),
                ('direccionDispositivo', models.CharField(blank=True, max_length=600, null=True, verbose_name='Dirección dispositivo')),
                ('numeroContador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Número contador')),
                ('nombreContador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre contador')),
            ],
            options={
                'verbose_name': 'AMRContador',
                'verbose_name_plural': 'AMRContador',
                'db_table': 'g_AMRContador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmpLectura', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Tiempo de Lectura')),
                ('totalImpEnerg', models.FloatField(blank=True, null=True, verbose_name='Total importe de energía activa (kWh)')),
                ('t1ImpEnerg', models.FloatField(blank=True, null=True, verbose_name='T1 importe de energía activa (kWh)')),
                ('t2ImpEnerg', models.FloatField(blank=True, null=True, verbose_name='T2 importe de energía activa (kWh)')),
                ('t3ImpEnerg', models.FloatField(blank=True, null=True, verbose_name='T3 importe de energía activa (kWh)')),
                ('totalExpEnerg', models.FloatField(blank=True, null=True, verbose_name='Total exporte de energía activa (kWh)')),
                ('t1ExpEnerg', models.FloatField(blank=True, null=True, verbose_name='T1 exporte de energía activa (kWh)')),
                ('t2ExpEnerg', models.FloatField(blank=True, null=True, verbose_name='T2 exporte de energía activa (kWh)')),
                ('t3ExpEnerg', models.FloatField(blank=True, null=True, verbose_name='T3 exporte de energía activa (kWh)')),
                ('totalImpReacEnerg', models.FloatField(blank=True, null=True, verbose_name='Total importe de energía reactiva (kvarh)')),
                ('t1ImpMaxDeman', models.FloatField(blank=True, null=True, verbose_name='T1 importe activo maximo demandado (kW)')),
                ('t2ImpMaxDeman', models.FloatField(blank=True, null=True, verbose_name='T2 importe activo maximo demandado (kW)')),
                ('t3ImpMaxDeman', models.FloatField(blank=True, null=True, verbose_name='T3 importe activo maximo demandado (kW)')),
                ('t1ExpMaxDeman', models.FloatField(blank=True, null=True, verbose_name='T1 exporte activo maximo demandado (kW)')),
                ('t2ExpMaxDeman', models.FloatField(blank=True, null=True, verbose_name='T2 exporte activo maximo demandado (kW)')),
                ('t3ExpMaxDeman', models.FloatField(blank=True, null=True, verbose_name='T3 exporte activo maximo demandado (kW)')),
                ('imporActPoder', models.FloatField(blank=True, null=True, verbose_name='Importe activo de poder (kW)')),
                ('exporActPoder', models.FloatField(blank=True, null=True, verbose_name='Exporte activo de poder (kW)')),
                ('factPoder', models.FloatField(blank=True, null=True, verbose_name='Factor de poder')),
                ('faceAVolt', models.FloatField(blank=True, null=True, verbose_name='Face A de voltage (V)')),
                ('faceBVolt', models.FloatField(blank=True, null=True, verbose_name='Face B de voltage (V)')),
                ('faceCVolt', models.FloatField(blank=True, null=True, verbose_name='Face C de voltage (V)')),
                ('faceACurr', models.FloatField(blank=True, null=True, verbose_name='Face A de current (A)')),
                ('faceBCurr', models.FloatField(blank=True, null=True, verbose_name='Face B de current (A)')),
                ('faceCCurr', models.FloatField(blank=True, null=True, verbose_name='Face C de current (A)')),
                ('amrContador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amrContadorApp.amrcontador', verbose_name='AMR')),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Datos',
                'db_table': 'g_Dato',
                'managed': True,
            },
        ),
    ]
