# Generated by Django 3.1.5 on 2021-01-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amrContadorApp', '0003_auto_20210122_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='amrcontador',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='amrcontador',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
