# Generated by Django 3.1.5 on 2021-01-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amrContadorApp', '0004_auto_20210124_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='amrcontador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='amrcontador',
            name='telefono',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Teléfono'),
        ),
    ]
